# Generated by Django 4.1.6 on 2023-02-02 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTraduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'TiposTraducciones',
                'db_table': 'tipotraduccion',
            },
        ),
        migrations.CreateModel(
            name='Traduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('texto_traducido', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('tipo_traduccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traductor.tipotraduccion')),
            ],
            options={
                'verbose_name': 'Traducciones',
                'db_table': 'traduccion',
            },
        ),
    ]
